trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '/home/aerben/mslearn-tailspin-spacegame-web'
    arguments: '--configuration Release'